### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by christopher-schroeder** [bahlolab/superSTR#12]
Hey,
i am about to write a bioconda recipe, which makes things a lot easier to install. But for that it is required to have a version release. I would like to request a realease, also for reproducibility. Would you be so kind to make one?

**Comment by lfearnley** [comment]
Thanks for that @christopher-schroeder! A release with version number 1.0.0 has been created. The release only contains source files and not precompiled binaries - adding these is on the to-do for future releases.
