### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by wdecoster** [bahlolab/superSTR#21]
Hi, 

I realize that this gives you very little information to debug, so please let me know what I can do to gather more information about this error.
I installed superSTR using conda (mamba), and I am running this using slurm on BAM files. My jobs end up with a non-zero exit code after a few hours, printing to stderr:

```
*** stack smashing detected ***: <unknown> terminated
srun: error: mforge157: task 0: Aborted (core dumped)
```

Do you have an idea of how to solve this?

Wouter

**Comment by lfearnley** [comment]
Just double checking - strdust or superSTR?

**Comment by wdecoster** [comment]
Oh.  Let me fix that :-D

**Comment by lfearnley** [comment]
Haha, I know that feeling!

We haven't encountered a stack smash yet and will need to a bit of
additional information.

I think the first step for debug will be to build from source with the -g
flag, see if it still faults, and if so, try it under valgrind if available
using exp-sgcheck.

This should give a stack trace that'll be informative as to where things
are going awry.

**Comment by wdecoster** [comment]
> I think the first step for debug will be to build from source with the -g flag, see if it still faults

That already solved the problem :)
