### ISSUE TITLE
help with post-processing issue

### ISSUE THREAD

**Issue by fjmuzengyiheng** [bahlolab/superSTR#3]
Thank you for providing this outstanding repeat expansion detection tool.

I got my 4 samples(FastQ) processed, and 4 per_read.txt.gz files are ready.

The next step should be post-processing. 
Here is my command:
_python3 /cluster/home/zengyiheng/project/zyh-pipeline/superstr/superSTR/Python/multiparse.py --input input_dir/ --output output_dir/ -@ 4 -r 150_

Error occurred:
Traceback (most recent call last):
  File "/cluster/home/zengyiheng/project/zyh-pipeline/superstr/superSTR/Python/multiparse.py", line 181, in <module>
    manifest_path = os.path.abspath(args.manifest_path)
  File "/cluster/home/zengyiheng/.conda/envs/superstr/lib/python3.8/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Could you please be so kind to help me with this problem? Thank you!

**Comment by FangfeiHu** [comment]
Hi @fjmuzengyiheng, I encountered the same problem with you when post-processing one sample. Did you find how to solve it?

**Comment by fjmuzengyiheng** [comment]
> > > Hi @fjmuzengyiheng, I encountered the same problem with you when post-processing one sample. Did you find how to solve it?
> > 
> > 
> > No, I still cannot figure it out. Perhaps we can 加个微信！（Wechat: 1590599948）
> 
> Sorry I didn't find your WeChat account. Could you check if the numbers are right? It seems like a phone number but lost one number.

aaah, 15905999048 is correct!

**Comment by lfearnley** [comment]
Apologies for the delayed response; I'm afraid that when transferring this repository to my lab's account I dropped out of the notifications for issues.

I'll have a patch up for this shortly!

**Comment by lfearnley** [comment]
I've temporarily disabled running superSTR's post-processing without a manifest file.

Downstream statistical analysis (outlier detection and motif screening) requires and relies on the presence of a label telling the software what each sample is; whether it's a case, unknown or control. This label information is added during the post-processing step, so multiparse.py is complaining about the absence of a manifest.

I've updated multiparse.py and the relevant documentation for the package; again, my apologies for the delayed reply, and please let me know if there's anything else I can help you with!
