### ISSUE TITLE
fatal error: kseq.h: No such file or directory

### ISSUE THREAD

**Issue by hchetia** [bahlolab/superSTR#4]
Hi I am trying to install superstr but getting the foll. error when running cmake . && make-

Scanning dependencies of target superstr
[  8%] Building C object CMakeFiles/superstr.dir/main.c.o
softwares/superSTR/C/main.c:8:18: fatal error: kseq.h: No such file or directory
 #include <kseq.h>
                  ^
compilation terminated.
make[2]: *** [CMakeFiles/superstr.dir/build.make:83: CMakeFiles/superstr.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/superstr.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

**Comment by lfearnley** [comment]
Hi @hchetia!

This is an error where superSTR isn't finding the path to your htslib install. You'll need to set the HTSLIB_ROOT environment variable in your shell to be the path to the htslib libraries using something like `export HTSLIB_ROOT=<your path here>`.

The only potential issue that I'm aware of with this is that sometimes there can be some issues with module systems (commonly found in HPC systems); if you're using a copy of htslib that has been installed through this, make sure you `module load` the htslib when using superSTR.

**Comment by hchetia** [comment]
Hi @lfearnley 
I followed your advice and superSTR installed successfully.
Thanks.
